language: python

python:
    - '3.7'
services:
    - postgresql
install:
- pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER kddgyphr WITH PASSWORD "VAwGR4cdvbUtY1x8o4czPyU-NACRxZFH ;"
  - psql -c "ALTER USER kddgyphr CREATEDB;"
script:
- python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: 7f20f782-93fd-4916-b884-a4d9c6f04cb2
    app: quick-tutor
