language: python

python:
    - '3.7'

install:
- pip install -r requirements.txt
- sudo systemctl start postgresql
- sudo systemctl enable postgresql

script:
- python manage.py test

# deploy:
#   provider: heroku
#   api_key:
#     secure: 7f20f782-93fd-4916-b884-a4d9c6f04cb2
#     app: quick-tutor
