# Generated by Django 3.0.2 on 2020-04-27 08:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(default='Name', max_length=200)),
                ('student_tutor', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('available', models.BooleanField(default=False)),
                ('tutor_notifications', models.IntegerField(default=0)),
                ('student_notifications', models.IntegerField(default=0)),
                ('venmo', models.CharField(default='', max_length=200)),
                ('student_year_in_school', models.CharField(choices=[('1Y', 'First Year'), ('2Y', 'Second Year'), ('3Y', 'Third Year'), ('4Y', 'Fourth Year'), ('GR', 'Graduate')], default='1Y', max_length=2)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('suggestion_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=200)),
                ('subject_text', models.TextField(default='')),
                ('modified_date', models.DateTimeField(default=datetime.datetime(2020, 4, 27, 8, 0, 52, 20958, tzinfo=utc))),
                ('contact_info', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
                ('progress', models.IntegerField(choices=[(1, 'PENDING'), (2, 'CANCELED'), (3, 'ACCEPTED'), (4, 'DECLINED'), (5, 'COMPLETED')], default=1)),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_requester', to='polls.Student')),
                ('tutor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested_tutor', to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
