# Generated by Django 3.0.2 on 2020-04-16 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 1, 48, 18, 435697, tzinfo=utc), verbose_name='date published'),
        ),
    ]
