# Generated by Django 3.0.2 on 2020-04-15 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 17, 23, 19, 401253, tzinfo=utc), verbose_name='date published'),
        ),
    ]
