# Generated by Django 3.0.2 on 2020-02-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_sugegstion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sugegstion',
            new_name='Suggestion',
        ),
    ]
