# Generated by Django 3.0.2 on 2020-04-15 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200415_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='progress',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 0, 50, 601676, tzinfo=utc), verbose_name='date published'),
        ),
    ]
