# Generated by Django 3.0.2 on 2020-04-17 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200416_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 3, 36, 48, 49729, tzinfo=utc), verbose_name='date published'),
        ),
    ]
