# Generated by Django 3.0.2 on 2020-04-27 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200427_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='student_archived',
            new_name='archived_student',
        ),
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='tutor_archived',
            new_name='archived_tutor',
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 10, 58, 56, 518794, tzinfo=utc)),
        ),
    ]
