# Generated by Django 3.0.2 on 2020-04-28 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200427_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 0, 10, 28, 627338, tzinfo=utc)),
        ),
    ]
