# Generated by Django 3.0.2 on 2020-04-15 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200415_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 19, 11, 40, 288026, tzinfo=utc), verbose_name='date published'),
        ),
    ]
