# Generated by Django 3.0.2 on 2020-04-22 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200417_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 19, 48, 41, 629021, tzinfo=utc), verbose_name='date published'),
        ),
    ]
