# Generated by Django 3.0.2 on 2020-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200204_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=200)),
                ('student_last_name', models.CharField(max_length=200)),
                ('student_email', models.CharField(max_length=200)),
                ('student_year_in_school', models.CharField(choices=[('1Y', 'First Year'), ('2Y', 'Second Year'), ('3Y', 'Third Year'), ('4Y', 'Fourth Year'), ('GR', 'Graduate')], default='1Y', max_length=2)),
            ],
        ),
    ]
