# Generated by Django 3.0.2 on 2020-04-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200323_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_last_name',
        ),
    ]
