# Generated by Django 3.0.2 on 2020-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_year_in_school',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1Y', 'First Year'), ('2Y', 'Second Year'), ('3Y', 'Third Year'), ('4Y', 'Fourth Year'), ('GR', 'Graduate Student')], default='1Y', max_length=2),
        ),
    ]
