# Generated by Django 3.0.2 on 2020-04-28 02:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200427_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='student_message',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='tutor_message',
        ),
        migrations.AlterField(
            model_name='tutorrequest',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 2, 53, 46, 746527, tzinfo=utc)),
        ),
    ]
