# Generated by Django 3.0.2 on 2020-04-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200402_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='skills',
            new_name='need_help_with',
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('subject_text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('in_progress', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
    ]
