# Generated by Django 3.0.2 on 2020-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200408_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.CharField(default='Somewhere', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_name',
            field=models.CharField(default='Name', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
