# Generated by Django 3.0.2 on 2020-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_student_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='venmo',
            field=models.CharField(default='Venmo', max_length=200),
        ),
    ]
