# Generated by Django 3.0.2 on 2020-04-14 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_student_venmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='my_requests',
            field=models.ManyToManyField(blank=True, related_name='tutor_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='student_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
